# Generated by Django 6.0 on 2025-12-31 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=56, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ttl_seconds', models.IntegerField(blank=True, null=True)),
                ('max_view', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pastes',
                'indexes': [models.Index(fields=['created_at'], name='pastes_created_eda8ec_idx')],
            },
        ),
    ]
